FROM python:3.8

ENV MICRO_SERVICE=/home/app/webapp

RUN mkdir -p $MICRO_SERVICE

WORKDIR $MICRO_SERVICE

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

# Copy source code to /src in container
COPY src/ $MICRO_SERVICE

# Install app and dependencies into /src in container
RUN pip install -r requirements.txt

# Document the port the app listens on
EXPOSE 8080

# Run this command (starts the app) when the container starts
CMD streamlit run auth.py